### ISSUE TITLE
リンク切れ

### ISSUE THREAD

**Issue by esperecyan** [gree/hubs-docs-jp#2]
以下のページで、リンクURL末尾に `.html` が付いているためにリンク切れしています。

- https://github.com/gree/hubs-docs-jp/wiki/welcome
	+ 自分のアバターをアップロード
	+ Spoke
- https://github.com/gree/hubs-docs-jp/wiki/intro-avatars
	+ 高度なアバターカスタマイズ
	+ 高度なアバターカスタマイズ
- https://github.com/gree/hubs-docs-jp/wiki/intro-events
	+ Hubsの概要
	+ Hubsの操作方法を理解する
	+ Spokeでクリエイティブ・コモンズライセンスで共有されている既存のシーンをリミックス
	+ 以下の手順で、部屋の中からシーンを変更します。
	+ Discord Bot
	+ ルームモデレーターへの昇格
	+ 一時的にユーザーをキックする
- https://github.com/gree/hubs-docs-jp/wiki/hubs-faq
	+ オブジェクトコントロール
	+ 対応デバイス & ブラウザ
	+ こちら
	+ カメラモード
	+ カスタムアバターの作成
	+ ルーム設定
	+ トラブルシューティング
	+ トラブルシューティング
	+ トラブルシューティング
- https://github.com/gree/hubs-docs-jp/wiki/creators-advanced-avatar-customization
	+ カスタムアバターの作成
	+ シーンの最適化
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-troubleshooting
	+ 新しいスタックリリースにアップグレード
	+ バージョン1.1.0を使用しているかどうかを確認してください
	+ バージョン1.1.0を使用しているかどうかを確認

以下のページで、リンクURL末尾に `.md` が付いているために、ソースへのリンクになっています。

- https://github.com/gree/hubs-docs-jp/wiki/sharing-avatar-links-privately
	+ create a custom avatar
- https://github.com/gree/hubs-docs-jp/wiki/hubs-room-settings
	+ コンテンツキュレーションガイドライン
- https://github.com/gree/hubs-docs-jp/wiki/hubs-discord-bot
	+ Hubs Cloud serverにボットを追加
- https://github.com/gree/hubs-docs-jp/wiki/spoke-creating-projects
	+ コンテンツ
	+ アーキテクチャキット
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-discord-bot
	+ Hubs Discord Bot
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-troubleshooting
	+ スタックガイドの更新 
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-estimated-cost-charts
	+ Hubs Cloud AWSコスト
- 次のページのすべてのWiki内リンク
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-intro
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-getting-started
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-faq
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-importing-content
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-asset-packs
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-customizing-look-and-feel
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-managing-content
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-adding-administrators
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-quick-start
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-domain-recipes
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-updating-the-stack
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-backup-and-restore
	
	
その他

- https://github.com/gree/hubs-docs-jp/wiki/hubs-troubleshooting
	+ `https://webvr.info/samples/XX-vr-controllers.html` と本文が繋がってリンク切れしている
- https://github.com/gree/hubs-docs-jp/wiki/spoke-creating-projects
	+ hubs.mozilla.com/speak
- https://github.com/gree/hubs-docs-jp/wiki/spoke-publish-scenes
	+  Floorplan(フロアプラン)
- https://github.com/gree/hubs-docs-jp/wiki/creators-advanced-avatar-customization
	+ エクスポートされた GLB
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-importing-content
	+ Spokeドキュメント
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-enable-scene-editor
	+ Scene Editor
- 次のページの「管理コンソール」
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-permissive-rooms
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-enable-media-browser
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-custom-smtp
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-accessing-servers
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-content-cdn
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-discord-bot
	+ Admin Console
	+ 管理コンソール
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-quick-start
	`https://hubs.mozilla.com/cloud` と本文が繋がってリンク切れしている

**Comment by kaitas** [comment]
@esperecyan ご指摘ありがとうございます！

原作や将来的な本家へのフィードバックとしてどうしようか…という判断のまま残ってしまった感じです。
ただここでの公開はWikiなので、ご指摘の通り修正したほうが良いですね。

上のほうから軽く手直ししてみましたが、けっこう数があるので、置き換えで処理してみようと思います。
また終わりましたらお伝えします。

**Comment by kaitas** [comment]
リンクURL末尾の `.html` の削除と、本家ドキュメントとの更新確認を行いました。
`#tag` については日本語化しました（本家との互換性をとるとセクションタイトルを英語にする必要があるので）。

- https://github.com/gree/hubs-docs-jp/wiki/welcome

- https://github.com/gree/hubs-docs-jp/wiki/intro-avatars

- https://github.com/gree/hubs-docs-jp/wiki/intro-events
	+ Hubsを使ったイベントの主催や会議に関して追加の質問がある場合、hubs@mozzila.comへの連絡か [Hubs Community Discord Server](https://discord.gg/wHmY4nd)に参加して #conferences チャンネルを確認してください。
	+ [原文](https://hubs.mozilla.com/docs/intro-events.html)が改訂されました。
	+ If you have additional questions about hosting events or conferences using Hubs, please get in touch by filling out the Hubs event interest form or join the Hubs Community Discord Server, and check out the #conferences channel.
	+ Hubsを使用したイベントやカンファレンスの開催について追加の質問がある場合は、Hubsのイベントリクエストフォームに記入するか、Hubs Community Discord Serverに参加して、#conferencesチャンネルをチェックしてください。

- https://github.com/gree/hubs-docs-jp/wiki/hubs-faq
FAQに追加があったので加筆
- https://hubs.mozilla.com/docs/hubs-faq.html
	+ Mozilla にお金を払って X, Y, Z の作業をしてもらうことはできますか？
	+ Hubsでバーチャルイベントを開催できますか？
	+ 機能Xの追加を検討しましたか？
	+ 他に何かお困りですか？


- https://github.com/gree/hubs-docs-jp/wiki/creators-advanced-avatar-customization

- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-troubleshooting


以下のページで、リンクURL末尾に `.md` が付いているために、ソースへのリンクになっています。

- https://github.com/gree/hubs-docs-jp/wiki/sharing-avatar-links-privately
	+ 翻訳しました：アバターリンクを非公開で共有する

- https://github.com/gree/hubs-docs-jp/wiki/hubs-room-settings

- https://github.com/gree/hubs-docs-jp/wiki/hubs-discord-bot

- https://github.com/gree/hubs-docs-jp/wiki/spoke-creating-projects

- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-discord-bot

- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-troubleshooting

- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-estimated-cost-charts

- 次のページのすべてのWiki内リンク
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-intro
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-getting-started
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-faq
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-importing-content
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-asset-packs
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-customizing-look-and-feel
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-managing-content
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-adding-administrators
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-quick-start
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-domain-recipes
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-updating-the-stack
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-backup-and-restore

→目で確認しながら置換してみましたが抜け漏れがないかご協力頂ければ幸いです。
	
	
その他

- https://github.com/gree/hubs-docs-jp/wiki/hubs-troubleshooting
	+ `https://webvr.info/samples/XX-vr-controllers.html` と本文が繋がってリンク切れしている
→解決

- https://github.com/gree/hubs-docs-jp/wiki/spoke-creating-projects
	+ hubs.mozilla.com/speak
→珍しいバグですね！解決。

- https://github.com/gree/hubs-docs-jp/wiki/spoke-publish-scenes
	+  Floorplan(フロアプラン)
→Floorplanと言いつつ、本家はタイトルの系が異なり[spoke-physics-and-navigation.md](https://github.com/gree/hubs-docs-jp/wiki/spoke-physics-and-navigation)のようなので 、「Floorplan要素(物理とナビゲーション)」としてリンクさせておきました。
[本家](https://hubs.mozilla.com/docs/physics-and-navigation.html)

- https://github.com/gree/hubs-docs-jp/wiki/creators-advanced-avatar-customization
	+ エクスポートされた GLB
本家も間違っているのですが、
- https://hubs.mozilla.com/docs/creators-advanced-avatar-customization.html
多分これかな…
- https://github.com/MozillaReality/hubs-avatar-pipelines/tree/master/Exported%20GLB%20models


- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-importing-content
	+ Spokeドキュメント
→本家のリンク間違いですね、[指摘しておきました](https://discordapp.com/channels/498741086295031808/639565625685180443/772101460753121290)。

- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-enable-scene-editor
	+ Scene Editor


- https://github.com/gree/hubs-docs-jp/wiki/hubs-troubleshooting
	+ 本家の改訂あり
	+ 「接続できません」というエラーは、ファイアウォールが原因で発生することがよくあります。 これを修正するには、別のインターネット接続を使用するか、ルーターのファイアウォールのHubsのUDPおよびTCPでポート20000〜65535を開きます。 IEEEVRのような自己ホストバージョンのHubsの場合、これらのポート番号はUDPおよびTCPでは49152-60999であることに注意してください。 また、UDPおよびTCPでポート19302を開く必要があります。
	+ An error that says "unable to connect" is often caused by a firewall. At a minimum, Hubs needs your computer to connect to external ports 80 and 443, both via TLS. Ideally, you should also open up ports 51610-65535 on UDP and TCP for Hubs on your router's firewall. Note that for self-hosted versions of Hubs you need to open ports 49152-60999 on UDP and TCP. You will also need to open port 19302 on UDP and TCP.
	+ →「接続できません」というエラーは、多くの場合、ファイアウォールが原因で発生します。最低限、HubsはコンピュータがTLSを介して外部ポート80と443に接続する必要があります。理想的には、ルータのファイアウォールでHubs用のUDPおよびTCPポート51610-65535を開く必要があります。Hubs の自己ホスト版では、UDPとTCPで ポート 49152-60999 を開く必要があることに注意してください。また、UDPとTCPでポート19302も開く必要があります。

ドキュメントに追加あり
- https://hubs.mozilla.com/docs/hubs-cloud-aws-updating-the-stack.html#upgrade-to-a-new-stack-release
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-updating-the-stack
	+ 新しいスタックリリースへのアップグレード
	+ バージョン1.1.0の場合での確認
	+ ↑実際にFirefoxで試してみているのですが、何を確認しろと言っているのかよくわからない…。（[原文](https://hubs.mozilla.com/docs/hubs-cloud-aws-updating-the-stack.html#check-if-youre-on-version-110)）

「ライティングと影」を追加
- https://github.com/gree/hubs-docs-jp/wiki/spoke-lighting-and-shadows

最近、コミュニティ貢献者により本家が加筆されているようなので今後、追従させていきたいですね。
https://github.com/MozillaReality/hubs-docs/commits/master

**Comment by kaitas** [comment]
@esperecyan 
以下はご指摘の内容がよくわかりませんでした。

- 次のページの「管理コンソール」
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-permissive-rooms
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-enable-media-browser
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-custom-smtp
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-accessing-servers
	+ https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-content-cdn
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-discord-bot
	+ Admin Console
	+ 管理コンソール
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-quick-start
	`https://hubs.mozilla.com/cloud` と本文が繋がってリンク切れしている

**Comment by kaitas** [comment]
こちらは修正できたと思います
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-quick-start
 + https://hubs.mozilla.com/cloud と本文が繋がってリンク切れしている

**Comment by esperecyan** [comment]
修正ありがとうございます！

管理コンソールについては勘違いでした。申し訳ございません。

あと、リストアップ漏れがありました。
- https://github.com/gree/hubs-docs-jp/wiki/intro-hubs
    + 説明

アンカーの修正についてですが、一部アンカー文字列が合っていないのと、最初のコメントでリストアップしていない所でリンク切れがありました。
- https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-troubleshooting
    + 誤: https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-updating-the-stack#バージョン1.1.0の場合での確認
    + 正: https://github.com/gree/hubs-docs-jp/wiki/hubs-cloud-aws-updating-the-stack#バージョン110の場合での確認
- https://github.com/gree/hubs-docs-jp/wiki/hubs-faq
    + 誤: https://github.com/gree/hubs-docs-jp/wiki/hubs-create-join-rooms#対応デバイス＆ブラウザ
    + 正: https://github.com/gree/hubs-docs-jp/wiki/hubs-create-join-rooms#対応デバイスブラウザ
- https://github.com/gree/hubs-docs-jp/wiki/hubs-features
    + ルームの共有ダイアログ
    + を開くのと同じ方法でEmojiスポナーを表示する

なおアンカーの互換性についてですが、次のように `<a>` タグを入れると任意のアンカーを設定できるので、こちらのようにしても良いかと思います。

```md
#### <a id="check-if-youre-on-version-110"></a>バージョン1.1.0の場合での確認
```

**Comment by esperecyan** [comment]
メニューの「カスタムクライアントをビルド」がリンク切れしているようです。  
(誤) build-custom-client  
(正) dev-build-custom-client

**Comment by kaitas** [comment]
確認が遅くなりましたが、先ほど全部修正対応終わったと思います。
また新しいUIについては時間かかりそうなので以下のように修正しました。

## ユーザーインターフェース(旧バージョン)
(訳注)改定された新バージョンのマニュアルは[こちら](https://hubs.mozilla.com/docs/hubs-features.html)

新しく Issue #3 として起こしておきます

**Comment by esperecyan** [comment]
確認しました。修正ありがとうございます！
