### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by neon-izm** [gree/hubs-docs-jp#4]
https://vr.gree.net/lab/demo/hubs/
内にある http://HubsDocsJp のurlにリンク先が存在しません。

適宜置き換えをお願いします。

**Comment by kaitas** [comment]
おお...これは
http://j.mp/HubsDocsJp
の誤りですね！
修正させていただきます

**Comment by kaitas** [comment]
Fixed:
https://vr.gree.net/lab/demo/hubs/

**Comment by neon-izm** [comment]
確認しました！感謝です
